apiVersion: tekton.dev/v1beta1
kind: EventListener
serviceAccountName: github-push
metadata:
  name: github-push
spec:
  triggers:
      bindings:
        name: binding-github-push
      template:
        name: template-github-push
