apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-push-pipeline
spec:
  tasks: 
  - name: github-push-task
    workspaces: 
    - name: source
      workspace: pipeline-workspace
    params:
    - name: URL
      description: URL of the repository to be cloned.
    taskRef:
      name: the-task