apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-push-pipeline
spec:
  params:
    - name: URL
      description: URL of the repository to be cloned.
  workspaces: 
  - name: source
    workspace: pipeline-workspace
  tasks: 
    - name: github-push-task
      taskRef:
        name: the-task
      params:
        - name: URL
          value: $(params.URL)