apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-push-pipeline
spec:
  tasks: 
  - name: github-push-task
    workspaces: 
    - name: source
      workspace: pipeline-workspace
    taskRef:
      name: the-task