apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding-github-push
spec:
  params:
  - name: URL
    value: "$(event.repository.clone_url)"
  - name: REVISION
    value: "$(event.pull_request.head.sha)"
  - name: NAMESPACE
    value: testapp
  - name: DEPLOYMENT
    value: testapp

---

apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template-github-push
params:
- name: URL
  description: The repository url to build and deploy.
- name: REVISION
  description: The revision to build and deploy.
- name: NAMESPACE
  description: The namespace is used by OpenShift's internal image registry to store the built image.
- name: DEPLOYMENT
  description: Name of the Deployment and the container name in the Deployment.
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        pipelineRef:
            name: github-push-pipeline